#!/bin/sh

dir="$(pwd)"
bin="$0"
while [ -L "${bin}" ]
do
    x="$(readlink "${bin}")"
    cd "$(dirname "${bin}")"
    bin="${x}"
done
cd "$(dirname "${bin}")"
home="$(pwd)"
cd "${dir}"
# insert magic here
exec node index.js "$@"
